create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.cms_pages (
  id uuid primary key default gen_random_uuid(),
  page_type text not null check (page_type in ('home','state','system','custom')),
  route_path text unique not null,
  slug text not null,
  jurisdiction_slug text,
  title text not null,
  h1 text not null,
  excerpt text not null default '',
  body text not null default '',
  meta_title text not null,
  meta_description text not null,
  robots_index boolean not null default true,
  status text not null default 'draft' check (status in ('draft','published')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists cms_pages_status_idx on public.cms_pages(status);
create index if not exists cms_pages_jurisdiction_idx on public.cms_pages(jurisdiction_slug);

create table if not exists public.menu_categories (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text unique not null,
  sort_order integer not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.menu_items (
  id uuid primary key default gen_random_uuid(),
  category_id uuid not null references public.menu_categories(id) on delete cascade,
  name text not null,
  price text not null default '',
  note text not null default '',
  sort_order integer not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(category_id, name)
);
create index if not exists menu_items_category_idx on public.menu_items(category_id, sort_order);

create table if not exists public.deals (
  id uuid primary key default gen_random_uuid(),
  title text unique not null,
  details text not null,
  status_text text not null default '',
  source_text text not null default '',
  starts_at date,
  ends_at date,
  sort_order integer not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.locations (
  id uuid primary key default gen_random_uuid(),
  jurisdiction_slug text not null,
  city text not null,
  address text not null default '',
  phone text not null default '',
  official_url text not null default '',
  sort_order integer not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(jurisdiction_slug, city, address)
);
create index if not exists locations_state_idx on public.locations(jurisdiction_slug, active, sort_order);

create table if not exists public.site_settings (
  id integer primary key default 1 check (id = 1),
  site_name text not null default 'Tim Hortons Menu USA Guide',
  site_tagline text not null default 'Independent U.S. menu, price, deal and location guide.',
  site_url text not null default 'https://example.com',
  ga_measurement_id text not null default '',
  adsense_client_id text not null default '',
  adsense_enabled boolean not null default false,
  adsense_home_slot text not null default '',
  adsense_article_slot text not null default '',
  adsense_sidebar_slot text not null default '',
  search_console_verification text not null default '',
  search_console_property text not null default '',
  ads_txt_publisher_id text not null default '',
  updated_at timestamptz not null default now()
);

create table if not exists public.subscribers (
  id bigint generated by default as identity primary key,
  email text unique not null,
  preferred_state text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Keep timestamps consistent.
drop trigger if exists cms_pages_updated_at on public.cms_pages;
create trigger cms_pages_updated_at before update on public.cms_pages for each row execute function public.set_updated_at();
drop trigger if exists menu_categories_updated_at on public.menu_categories;
create trigger menu_categories_updated_at before update on public.menu_categories for each row execute function public.set_updated_at();
drop trigger if exists menu_items_updated_at on public.menu_items;
create trigger menu_items_updated_at before update on public.menu_items for each row execute function public.set_updated_at();
drop trigger if exists deals_updated_at on public.deals;
create trigger deals_updated_at before update on public.deals for each row execute function public.set_updated_at();
drop trigger if exists locations_updated_at on public.locations;
create trigger locations_updated_at before update on public.locations for each row execute function public.set_updated_at();
drop trigger if exists subscribers_updated_at on public.subscribers;
create trigger subscribers_updated_at before update on public.subscribers for each row execute function public.set_updated_at();

-- Browser clients can read only published/active public content. Admin writes use protected server actions.
alter table public.admin_users enable row level security;
alter table public.cms_pages enable row level security;
alter table public.menu_categories enable row level security;
alter table public.menu_items enable row level security;
alter table public.deals enable row level security;
alter table public.locations enable row level security;
alter table public.site_settings enable row level security;
alter table public.subscribers enable row level security;

drop policy if exists "Published pages are public" on public.cms_pages;
create policy "Published pages are public" on public.cms_pages for select using (status = 'published');
drop policy if exists "Active categories are public" on public.menu_categories;
create policy "Active categories are public" on public.menu_categories for select using (active = true);
drop policy if exists "Active menu items are public" on public.menu_items;
create policy "Active menu items are public" on public.menu_items for select using (active = true);
drop policy if exists "Active deals are public" on public.deals;
create policy "Active deals are public" on public.deals for select using (active = true);
drop policy if exists "Active locations are public" on public.locations;
create policy "Active locations are public" on public.locations for select using (active = true);
drop policy if exists "Settings are public" on public.site_settings;
create policy "Settings are public" on public.site_settings for select using (true);
