export const jurisdictions = [
  {
    "name": "Alabama",
    "abbr": "AL",
    "slug": "alabama",
    "region": "Southeast",
    "hasVerifiedLocations": false,
    "cities": [],
    "officialStateUrl": "https://locations.timhortons.com/en/",
    "regionalNote": "No city is currently listed for this jurisdiction in the official U.S. Tim Hortons location directory."
  },
  {
    "name": "Alaska",
    "abbr": "AK",
    "slug": "alaska",
    "region": "West",
    "hasVerifiedLocations": false,
    "cities": [],
    "officialStateUrl": "https://locations.timhortons.com/en/",
    "regionalNote": "No city is currently listed for this jurisdiction in the official U.S. Tim Hortons location directory."
  },
  {
    "name": "Arizona",
    "abbr": "AZ",
    "slug": "arizona",
    "region": "Southwest",
    "hasVerifiedLocations": false,
    "cities": [],
    "officialStateUrl": "https://locations.timhortons.com/en/",
    "regionalNote": "No city is currently listed for this jurisdiction in the official U.S. Tim Hortons location directory."
  },
  {
    "name": "Arkansas",
    "abbr": "AR",
    "slug": "arkansas",
    "region": "South",
    "hasVerifiedLocations": false,
    "cities": [],
    "officialStateUrl": "https://locations.timhortons.com/en/",
    "regionalNote": "No city is currently listed for this jurisdiction in the official U.S. Tim Hortons location directory."
  },
  {
    "name": "California",
    "abbr": "CA",
    "slug": "california",
    "region": "West",
    "hasVerifiedLocations": false,
    "cities": [],
    "officialStateUrl": "https://locations.timhortons.com/en/",
    "regionalNote": "No city is currently listed for this jurisdiction in the official U.S. Tim Hortons location directory."
  },
  {
    "name": "Colorado",
    "abbr": "CO",
    "slug": "colorado",
    "region": "Mountain West",
    "hasVerifiedLocations": false,
    "cities": [],
    "officialStateUrl": "https://locations.timhortons.com/en/",
    "regionalNote": "No city is currently listed for this jurisdiction in the official U.S. Tim Hortons location directory."
  },
  {
    "name": "Connecticut",
    "abbr": "CT",
    "slug": "connecticut",
    "region": "Northeast",
    "hasVerifiedLocations": false,
    "cities": [],
    "officialStateUrl": "https://locations.timhortons.com/en/",
    "regionalNote": "No city is currently listed for this jurisdiction in the official U.S. Tim Hortons location directory."
  },
  {
    "name": "Delaware",
    "abbr": "DE",
    "slug": "delaware",
    "region": "Mid-Atlantic",
    "hasVerifiedLocations": true,
    "cities": [
      "Dover"
    ],
    "officialStateUrl": "https://locations.timhortons.com/en/locations-list/de/",
    "regionalNote": "Menu availability can differ by restaurant, service mode, daypart, and franchise pricing."
  },
  {
    "name": "Florida",
    "abbr": "FL",
    "slug": "florida",
    "region": "Southeast",
    "hasVerifiedLocations": true,
    "cities": [
      "Bradenton"
    ],
    "officialStateUrl": "https://locations.timhortons.com/en/locations-list/fl/",
    "regionalNote": "Menu availability can differ by restaurant, service mode, daypart, and franchise pricing."
  },
  {
    "name": "Georgia",
    "abbr": "GA",
    "slug": "georgia",
    "region": "Southeast",
    "hasVerifiedLocations": true,
    "cities": [
      "Alpharetta",
      "Atlanta",
      "Columbus",
      "Fairburn",
      "Jonesboro",
      "Newnan",
      "Suwanee"
    ],
    "officialStateUrl": "https://locations.timhortons.com/en/locations-list/ga/",
    "regionalNote": "Participating restaurants in this market may offer the southern U.S. Egg White Wrap recipe with American cheese."
  },
  {
    "name": "Hawaii",
    "abbr": "HI",
    "slug": "hawaii",
    "region": "Pacific",
    "hasVerifiedLocations": false,
    "cities": [],
    "officialStateUrl": "https://locations.timhortons.com/en/",
    "regionalNote": "No city is currently listed for this jurisdiction in the official U.S. Tim Hortons location directory."
  },
  {
    "name": "Idaho",
    "abbr": "ID",
    "slug": "idaho",
    "region": "Mountain West",
    "hasVerifiedLocations": false,
    "cities": [],
    "officialStateUrl": "https://locations.timhortons.com/en/",
    "regionalNote": "No city is currently listed for this jurisdiction in the official U.S. Tim Hortons location directory."
  },
  {
    "name": "Illinois",
    "abbr": "IL",
    "slug": "illinois",
    "region": "Midwest",
    "hasVerifiedLocations": false,
    "cities": [],
    "officialStateUrl": "https://locations.timhortons.com/en/",
    "regionalNote": "No city is currently listed for this jurisdiction in the official U.S. Tim Hortons location directory."
  },
  {
    "name": "Indiana",
    "abbr": "IN",
    "slug": "indiana",
    "region": "Midwest",
    "hasVerifiedLocations": true,
    "cities": [
      "Fort Wayne"
    ],
    "officialStateUrl": "https://locations.timhortons.com/en/locations-list/in/",
    "regionalNote": "Menu availability can differ by restaurant, service mode, daypart, and franchise pricing."
  },
  {
    "name": "Iowa",
    "abbr": "IA",
    "slug": "iowa",
    "region": "Midwest",
    "hasVerifiedLocations": false,
    "cities": [],
    "officialStateUrl": "https://locations.timhortons.com/en/",
    "regionalNote": "No city is currently listed for this jurisdiction in the official U.S. Tim Hortons location directory."
  },
  {
    "name": "Kansas",
    "abbr": "KS",
    "slug": "kansas",
    "region": "Great Plains",
    "hasVerifiedLocations": false,
    "cities": [],
    "officialStateUrl": "https://locations.timhortons.com/en/",
    "regionalNote": "No city is currently listed for this jurisdiction in the official U.S. Tim Hortons location directory."
  },
  {
    "name": "Kentucky",
    "abbr": "KY",
    "slug": "kentucky",
    "region": "Upper South",
    "hasVerifiedLocations": true,
    "cities": [
      "Ashland"
    ],
    "officialStateUrl": "https://locations.timhortons.com/en/locations-list/ky/",
    "regionalNote": "Menu availability can differ by restaurant, service mode, daypart, and franchise pricing."
  },
  {
    "name": "Louisiana",
    "abbr": "LA",
    "slug": "louisiana",
    "region": "Gulf South",
    "hasVerifiedLocations": false,
    "cities": [],
    "officialStateUrl": "https://locations.timhortons.com/en/",
    "regionalNote": "No city is currently listed for this jurisdiction in the official U.S. Tim Hortons location directory."
  },
  {
    "name": "Maine",
    "abbr": "ME",
    "slug": "maine",
    "region": "New England",
    "hasVerifiedLocations": true,
    "cities": [
      "Bangor",
      "Brewer",
      "Caribou",
      "Houlton",
      "Madawaska",
      "Presque Isle"
    ],
    "officialStateUrl": "https://locations.timhortons.com/en/locations-list/me/",
    "regionalNote": "Menu availability can differ by restaurant, service mode, daypart, and franchise pricing."
  },
  {
    "name": "Maryland",
    "abbr": "MD",
    "slug": "maryland",
    "region": "Mid-Atlantic",
    "hasVerifiedLocations": false,
    "cities": [],
    "officialStateUrl": "https://locations.timhortons.com/en/",
    "regionalNote": "No city is currently listed for this jurisdiction in the official U.S. Tim Hortons location directory."
  },
  {
    "name": "Massachusetts",
    "abbr": "MA",
    "slug": "massachusetts",
    "region": "New England",
    "hasVerifiedLocations": false,
    "cities": [],
    "officialStateUrl": "https://locations.timhortons.com/en/",
    "regionalNote": "No city is currently listed for this jurisdiction in the official U.S. Tim Hortons location directory."
  },
  {
    "name": "Michigan",
    "abbr": "MI",
    "slug": "michigan",
    "region": "Great Lakes",
    "hasVerifiedLocations": true,
    "cities": [
      "Adrian",
      "Alma",
      "Ann Arbor",
      "Bay City",
      "Belleville",
      "Birmingham",
      "Bloomfield",
      "Brighton",
      "Brooklyn",
      "Brownstown",
      "Burton",
      "Cadillac",
      "Canton",
      "Cedar Springs",
      "Chesterfield",
      "Clarkston",
      "Clawson",
      "Clinton",
      "Clinton Township",
      "Clio",
      "Commerce",
      "Davison",
      "Dearborn",
      "Dearborn Heights",
      "Detroit",
      "Dewitt",
      "Dundee",
      "Eastpointe",
      "Essexville",
      "Farmington Hills",
      "Fenton",
      "Flat Rock",
      "Flint",
      "Frankenmuth",
      "Fraser",
      "Garden City",
      "Gaylord",
      "Grand Blanc",
      "Grand Rapids",
      "Harper Woods",
      "Hartland",
      "Hazel Park",
      "Holland",
      "Holly",
      "Howell",
      "Imlay City",
      "Jackson",
      "Kentwood",
      "Lake Orion",
      "Lambertville",
      "Lansing",
      "Lapeer",
      "Lenox",
      "Lincoln Park",
      "Livonia",
      "Lowell",
      "Lyon Township",
      "Macomb",
      "Madison Heights",
      "Marysville",
      "Melvindale",
      "Midland",
      "Monroe",
      "Mount Pleasant",
      "Muskegon",
      "New Hudson",
      "Northville",
      "Norton Shores",
      "Novi",
      "Oak Park",
      "Owosso",
      "Oxford",
      "Plymouth",
      "Pontiac",
      "Port Huron",
      "Portage",
      "Redford",
      "Richmond",
      "Rochester Hills",
      "Romeo",
      "Romulus",
      "Roseville",
      "Royal Oak",
      "Saginaw",
      "Saint Clair",
      "Saint Clair Shores",
      "Saline",
      "Shelby",
      "Shelby Township",
      "Southfield",
      "Southgate",
      "Sterling Heights",
      "Taylor",
      "Tecumseh",
      "Trenton",
      "Troy",
      "Utica",
      "Van Buren",
      "Walled Lake",
      "Warren",
      "Waterford",
      "Wayne",
      "West Branch",
      "Westland",
      "White Lake",
      "Woodhaven",
      "Wyandotte",
      "Ypsilanti"
    ],
    "officialStateUrl": "https://locations.timhortons.com/en/locations-list/mi/",
    "regionalNote": "Participating restaurants in this market may offer the northern U.S. Egg White Wrap recipe with Swiss cheese and creamy herb sauce."
  },
  {
    "name": "Minnesota",
    "abbr": "MN",
    "slug": "minnesota",
    "region": "Upper Midwest",
    "hasVerifiedLocations": false,
    "cities": [],
    "officialStateUrl": "https://locations.timhortons.com/en/",
    "regionalNote": "No city is currently listed for this jurisdiction in the official U.S. Tim Hortons location directory."
  },
  {
    "name": "Mississippi",
    "abbr": "MS",
    "slug": "mississippi",
    "region": "Deep South",
    "hasVerifiedLocations": false,
    "cities": [],
    "officialStateUrl": "https://locations.timhortons.com/en/",
    "regionalNote": "No city is currently listed for this jurisdiction in the official U.S. Tim Hortons location directory."
  },
  {
    "name": "Missouri",
    "abbr": "MO",
    "slug": "missouri",
    "region": "Midwest",
    "hasVerifiedLocations": false,
    "cities": [],
    "officialStateUrl": "https://locations.timhortons.com/en/",
    "regionalNote": "No city is currently listed for this jurisdiction in the official U.S. Tim Hortons location directory."
  },
  {
    "name": "Montana",
    "abbr": "MT",
    "slug": "montana",
    "region": "Mountain West",
    "hasVerifiedLocations": false,
    "cities": [],
    "officialStateUrl": "https://locations.timhortons.com/en/",
    "regionalNote": "No city is currently listed for this jurisdiction in the official U.S. Tim Hortons location directory."
  },
  {
    "name": "Nebraska",
    "abbr": "NE",
    "slug": "nebraska",
    "region": "Great Plains",
    "hasVerifiedLocations": false,
    "cities": [],
    "officialStateUrl": "https://locations.timhortons.com/en/",
    "regionalNote": "No city is currently listed for this jurisdiction in the official U.S. Tim Hortons location directory."
  },
  {
    "name": "Nevada",
    "abbr": "NV",
    "slug": "nevada",
    "region": "West",
    "hasVerifiedLocations": false,
    "cities": [],
    "officialStateUrl": "https://locations.timhortons.com/en/",
    "regionalNote": "No city is currently listed for this jurisdiction in the official U.S. Tim Hortons location directory."
  },
  {
    "name": "New Hampshire",
    "abbr": "NH",
    "slug": "new-hampshire",
    "region": "New England",
    "hasVerifiedLocations": false,
    "cities": [],
    "officialStateUrl": "https://locations.timhortons.com/en/",
    "regionalNote": "No city is currently listed for this jurisdiction in the official U.S. Tim Hortons location directory."
  },
  {
    "name": "New Jersey",
    "abbr": "NJ",
    "slug": "new-jersey",
    "region": "Mid-Atlantic",
    "hasVerifiedLocations": true,
    "cities": [
      "Brick Township",
      "Cinnaminson",
      "Colonia",
      "Iselin",
      "Lacey",
      "Linden",
      "Mahwah",
      "North Bergen",
      "Paramus",
      "Pennsauken",
      "Raritan",
      "Stratford",
      "Upper Saddle River"
    ],
    "officialStateUrl": "https://locations.timhortons.com/en/locations-list/nj/",
    "regionalNote": "Participating restaurants in this market may offer the northern U.S. Egg White Wrap recipe with Swiss cheese and creamy herb sauce."
  },
  {
    "name": "New Mexico",
    "abbr": "NM",
    "slug": "new-mexico",
    "region": "Southwest",
    "hasVerifiedLocations": false,
    "cities": [],
    "officialStateUrl": "https://locations.timhortons.com/en/",
    "regionalNote": "No city is currently listed for this jurisdiction in the official U.S. Tim Hortons location directory."
  },
  {
    "name": "New York",
    "abbr": "NY",
    "slug": "new-york",
    "region": "Northeast",
    "hasVerifiedLocations": true,
    "cities": [
      "Akron",
      "Albion",
      "Alden",
      "Amherst",
      "Amityville",
      "Angola",
      "Arcade",
      "Batavia",
      "Bay Shore",
      "Bethpage",
      "Blasdell",
      "Brentwood",
      "Brockport",
      "Brooklyn",
      "Buffalo",
      "Canandaigua",
      "Canton",
      "Cassadaga",
      "Chaffee",
      "Cheektowaga",
      "Clarence",
      "Commack",
      "Darien Center",
      "Depew",
      "Derby",
      "Dunkirk",
      "East Amherst",
      "East Aurora",
      "East Meadow",
      "East Norwich",
      "East Rochester",
      "Eden",
      "Ellicottville",
      "Elma",
      "Elmont",
      "Evans Mills",
      "Franklin Square",
      "Fredonia",
      "Fresh Meadows",
      "Gates",
      "Geneseo",
      "Geneva",
      "Getzville",
      "Gowanda",
      "Grand Island",
      "Greece",
      "Hamburg",
      "Hauppauge",
      "Hempstead",
      "Henrietta",
      "Hicksville",
      "Hogansburg",
      "Holtsville",
      "Hornell",
      "Irving",
      "Islip",
      "Islip Terrace",
      "Jamaica",
      "Jamestown",
      "Kenmore",
      "Lackawanna",
      "Lakeview",
      "Lakewood",
      "Lancaster",
      "Levittown",
      "Lewiston",
      "Lockport",
      "Malone",
      "Massena",
      "Mayville",
      "Medford",
      "Medina",
      "Melville",
      "Mineola",
      "Morristown",
      "New York",
      "Newark",
      "Newfane",
      "Niagara Falls",
      "North Babylon",
      "North Chili",
      "North Tonawanda",
      "Ogdensburg",
      "Old Westbury",
      "Olean",
      "Orchard Park",
      "Ozone Park",
      "Patchogue",
      "Pembroke",
      "Penfield",
      "Piffard",
      "Pittsford",
      "Plainview",
      "Potsdam",
      "Rochester",
      "Ronkonkoma",
      "Roslyn Heights",
      "Salamanca",
      "Sanborn",
      "Seaford",
      "Smithtown",
      "South Wales",
      "Spencerport",
      "Springville",
      "Staten Island",
      "Stony Point",
      "Syracuse",
      "Tonawanda",
      "Uniondale",
      "Victor",
      "Wantagh",
      "Warsaw",
      "Watertown",
      "Webster",
      "West Seneca",
      "Westfield",
      "White Plains",
      "Williamsville",
      "Winthrop"
    ],
    "officialStateUrl": "https://locations.timhortons.com/en/locations-list/ny/",
    "regionalNote": "Participating restaurants in this market may offer the northern U.S. Egg White Wrap recipe with Swiss cheese and creamy herb sauce."
  },
  {
    "name": "North Carolina",
    "abbr": "NC",
    "slug": "north-carolina",
    "region": "Southeast",
    "hasVerifiedLocations": false,
    "cities": [],
    "officialStateUrl": "https://locations.timhortons.com/en/",
    "regionalNote": "No city is currently listed for this jurisdiction in the official U.S. Tim Hortons location directory."
  },
  {
    "name": "North Dakota",
    "abbr": "ND",
    "slug": "north-dakota",
    "region": "Great Plains",
    "hasVerifiedLocations": false,
    "cities": [],
    "officialStateUrl": "https://locations.timhortons.com/en/",
    "regionalNote": "No city is currently listed for this jurisdiction in the official U.S. Tim Hortons location directory."
  },
  {
    "name": "Ohio",
    "abbr": "OH",
    "slug": "ohio",
    "region": "Great Lakes",
    "hasVerifiedLocations": true,
    "cities": [
      "Akron",
      "Ashland",
      "Athens",
      "Beavercreek",
      "Bellefontaine",
      "Bowling Green",
      "Bucyrus",
      "Calcutta",
      "Cambridge",
      "Canal Winchester",
      "Chillicothe",
      "Circleville",
      "Columbus",
      "Coshocton",
      "Dayton",
      "Defiance",
      "Delaware",
      "Dublin",
      "Englewood",
      "Fairborn",
      "Findlay",
      "Fremont",
      "Gahanna",
      "Galion",
      "Grove City",
      "Groveport",
      "Heath",
      "Hilliard",
      "Holland",
      "Huber Heights",
      "Jackson",
      "Lancaster",
      "Lewis Center",
      "Logan",
      "Mansfield",
      "Marietta",
      "Marion",
      "Marysville",
      "Maumee",
      "Miamisburg",
      "Monroe",
      "Mount Vernon",
      "Mt Vernon",
      "New Albany",
      "Newark",
      "Oregon",
      "Pataskala",
      "Perrysburg",
      "Pickerington",
      "Piqua",
      "Plain City",
      "Portsmouth",
      "Powell",
      "Reynoldsburg",
      "Riverside",
      "Rossford",
      "Sidney",
      "South Bloomfield",
      "Springboro",
      "Springfield",
      "Steubenville",
      "Sunbury",
      "Sylvania",
      "Tiffin",
      "Toledo",
      "Troy",
      "Upper Arlington",
      "Urbana",
      "Van Wert",
      "Washington Court House",
      "Waverly",
      "Westerville",
      "Zanesville"
    ],
    "officialStateUrl": "https://locations.timhortons.com/en/locations-list/oh/",
    "regionalNote": "Participating restaurants in this market may offer the northern U.S. Egg White Wrap recipe with Swiss cheese and creamy herb sauce."
  },
  {
    "name": "Oklahoma",
    "abbr": "OK",
    "slug": "oklahoma",
    "region": "South Central",
    "hasVerifiedLocations": false,
    "cities": [],
    "officialStateUrl": "https://locations.timhortons.com/en/",
    "regionalNote": "No city is currently listed for this jurisdiction in the official U.S. Tim Hortons location directory."
  },
  {
    "name": "Oregon",
    "abbr": "OR",
    "slug": "oregon",
    "region": "Pacific Northwest",
    "hasVerifiedLocations": false,
    "cities": [],
    "officialStateUrl": "https://locations.timhortons.com/en/",
    "regionalNote": "No city is currently listed for this jurisdiction in the official U.S. Tim Hortons location directory."
  },
  {
    "name": "Pennsylvania",
    "abbr": "PA",
    "slug": "pennsylvania",
    "region": "Mid-Atlantic",
    "hasVerifiedLocations": true,
    "cities": [
      "Allentown",
      "Bradford",
      "Corry",
      "Duncannon",
      "Edinboro",
      "Erie",
      "Girard",
      "Hallstead",
      "Jefferson Township",
      "Meadville",
      "Warren"
    ],
    "officialStateUrl": "https://locations.timhortons.com/en/locations-list/pa/",
    "regionalNote": "Participating restaurants in this market may offer the northern U.S. Egg White Wrap recipe with Swiss cheese and creamy herb sauce."
  },
  {
    "name": "Rhode Island",
    "abbr": "RI",
    "slug": "rhode-island",
    "region": "New England",
    "hasVerifiedLocations": false,
    "cities": [],
    "officialStateUrl": "https://locations.timhortons.com/en/",
    "regionalNote": "No city is currently listed for this jurisdiction in the official U.S. Tim Hortons location directory."
  },
  {
    "name": "South Carolina",
    "abbr": "SC",
    "slug": "south-carolina",
    "region": "Southeast",
    "hasVerifiedLocations": false,
    "cities": [],
    "officialStateUrl": "https://locations.timhortons.com/en/",
    "regionalNote": "No city is currently listed for this jurisdiction in the official U.S. Tim Hortons location directory."
  },
  {
    "name": "South Dakota",
    "abbr": "SD",
    "slug": "south-dakota",
    "region": "Great Plains",
    "hasVerifiedLocations": false,
    "cities": [],
    "officialStateUrl": "https://locations.timhortons.com/en/",
    "regionalNote": "No city is currently listed for this jurisdiction in the official U.S. Tim Hortons location directory."
  },
  {
    "name": "Tennessee",
    "abbr": "TN",
    "slug": "tennessee",
    "region": "Southeast",
    "hasVerifiedLocations": true,
    "cities": [
      "Lebanon",
      "Mt Juliet",
      "Nashville"
    ],
    "officialStateUrl": "https://locations.timhortons.com/en/locations-list/tn/",
    "regionalNote": "Participating restaurants in this market may offer the southern U.S. Egg White Wrap recipe with American cheese."
  },
  {
    "name": "Texas",
    "abbr": "TX",
    "slug": "texas",
    "region": "South Central",
    "hasVerifiedLocations": true,
    "cities": [
      "Austin",
      "Bryan",
      "Cedar Park",
      "Houston",
      "Humble",
      "Katy",
      "Richmond",
      "Stafford"
    ],
    "officialStateUrl": "https://locations.timhortons.com/en/locations-list/tx/",
    "regionalNote": "Participating restaurants in this market may offer the southern U.S. Egg White Wrap recipe with American cheese."
  },
  {
    "name": "Utah",
    "abbr": "UT",
    "slug": "utah",
    "region": "Mountain West",
    "hasVerifiedLocations": false,
    "cities": [],
    "officialStateUrl": "https://locations.timhortons.com/en/",
    "regionalNote": "No city is currently listed for this jurisdiction in the official U.S. Tim Hortons location directory."
  },
  {
    "name": "Vermont",
    "abbr": "VT",
    "slug": "vermont",
    "region": "New England",
    "hasVerifiedLocations": false,
    "cities": [],
    "officialStateUrl": "https://locations.timhortons.com/en/",
    "regionalNote": "No city is currently listed for this jurisdiction in the official U.S. Tim Hortons location directory."
  },
  {
    "name": "Virginia",
    "abbr": "VA",
    "slug": "virginia",
    "region": "Mid-Atlantic",
    "hasVerifiedLocations": true,
    "cities": [
      "Norfolk"
    ],
    "officialStateUrl": "https://locations.timhortons.com/en/locations-list/va/",
    "regionalNote": "Participating restaurants in this market may offer the northern U.S. Egg White Wrap recipe with Swiss cheese and creamy herb sauce."
  },
  {
    "name": "Washington",
    "abbr": "WA",
    "slug": "washington",
    "region": "Pacific Northwest",
    "hasVerifiedLocations": false,
    "cities": [],
    "officialStateUrl": "https://locations.timhortons.com/en/",
    "regionalNote": "No city is currently listed for this jurisdiction in the official U.S. Tim Hortons location directory."
  },
  {
    "name": "West Virginia",
    "abbr": "WV",
    "slug": "west-virginia",
    "region": "Appalachia",
    "hasVerifiedLocations": true,
    "cities": [
      "Clarksburg",
      "Cross Lanes",
      "Morgantown",
      "Parkersburg",
      "Saint Albans",
      "Vienna",
      "Weirton",
      "Wheeling"
    ],
    "officialStateUrl": "https://locations.timhortons.com/en/locations-list/wv/",
    "regionalNote": "Menu availability can differ by restaurant, service mode, daypart, and franchise pricing."
  },
  {
    "name": "Wisconsin",
    "abbr": "WI",
    "slug": "wisconsin",
    "region": "Great Lakes",
    "hasVerifiedLocations": false,
    "cities": [],
    "officialStateUrl": "https://locations.timhortons.com/en/",
    "regionalNote": "No city is currently listed for this jurisdiction in the official U.S. Tim Hortons location directory."
  },
  {
    "name": "Wyoming",
    "abbr": "WY",
    "slug": "wyoming",
    "region": "Mountain West",
    "hasVerifiedLocations": false,
    "cities": [],
    "officialStateUrl": "https://locations.timhortons.com/en/",
    "regionalNote": "No city is currently listed for this jurisdiction in the official U.S. Tim Hortons location directory."
  },
  {
    "name": "District of Columbia",
    "abbr": "DC",
    "slug": "district-of-columbia",
    "region": "Mid-Atlantic",
    "hasVerifiedLocations": false,
    "cities": [],
    "officialStateUrl": "https://locations.timhortons.com/en/",
    "regionalNote": "No city is currently listed for this jurisdiction in the official U.S. Tim Hortons location directory."
  },
  {
    "name": "Puerto Rico",
    "abbr": "PR",
    "slug": "puerto-rico",
    "region": "Caribbean",
    "hasVerifiedLocations": false,
    "cities": [],
    "officialStateUrl": "https://locations.timhortons.com/en/",
    "regionalNote": "No city is currently listed for this jurisdiction in the official U.S. Tim Hortons location directory."
  }
] as const;

export type Jurisdiction = (typeof jurisdictions)[number];

export function getJurisdiction(slug: string) {
  return jurisdictions.find((item) => item.slug === slug);
}
